version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=myuser
      - POSTGRES_DB=billings
    ports:
      - '5434:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

#  app:
#    build: .
#    ports:
#      - '3000:3000'
#    environment:
#      NODE_ENV: development
#      POSTGRES_USER: myuser
#      POSTGRES_PASSWORD: mypassword
#      POSTGRES_DB: postgres
#    depends_on:
#      - postgres
